apiVersion: v1
kind: ConfigMap
metadata:
  name: teleport
data:
  teleport.yaml: |
    teleport:
      connection_limits:
        max_connections: 1000
        max_users: 250
      cache:
        enabled: true
        type: in-memory
        ttl: 20h
      log:
        severity: DEBUG
        output: stderr
        format:
          output: text
          extra_fields: [level, timestamp, component, caller]
      storage:
        type: etcd
        peers: ["http://trusted-cluster-01-etcd.trusted-cluster-01.svc.cluster.local:2379"]
        prefix: /teleport.secrets/
        tls_key_file: /var/certs/etcd/trusted-cluster-01-etcd.trusted-cluster-01.svc.cluster.local-key.pem
        tls_cert_file: /var/certs/etcd/trusted-cluster-01-etcd.trusted-cluster-01.svc.cluster.local.pem
        tls_ca_file: /var/certs/etcd/trusted-cluster-01-etcd.trusted-cluster-01.svc.cluster.local.ca.pem

        audit_sessions_uri: s3://trusted-cluster-sessions/recording?region=us-east-1&endpoint=minio.minio:9000&insecure=true&disablesse=true
        #insecure: true
    auth_service:
      enabled: true
      tokens:
       - trusted_cluster:Zs15b013ba25c99d3454336002cf9b20fb
      cluster_name: teleport.trusted-cluster-01.svc.cluster.local
      authentication:
        type: local
        second_factor: off
    kubernetes_service:
      enabled: false
      listen_addr: 0.0.0.0:3027
      kube_cluster_name: teleport.trusted-cluster-01.svc.cluster.local
    proxy_service:
      public_addr: 'teleport.trusted-cluster-01.svc.cluster.local:443'
      kube_listen_addr: 0.0.0.0:3026
      mysql_listen_addr: 0.0.0.0:3036
      enabled: true
    ssh_service:
      enabled: false
