---
apiVersion: v1
kind: Service
metadata:
  name: trusted-cluster-01-etcd
  namespace: trusted-cluster-01
spec:
  clusterIP: None
  ports:
  - port: 2379
    name: client
  - port: 2380
    name: peer
  selector:
    app: trusted-cluster-01-etcd
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd
  namespace: trusted-cluster-01
spec:
  selector:
    matchLabels:
      app: trusted-cluster-01-etcd
  serviceName: trusted-cluster-01-etcd
  replicas: 3
  template:
    metadata:
      labels:
        app: trusted-cluster-01-etcd
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: etcd
        image: quay.io/coreos/etcd:v3.5.1
        command:
          - /bin/sh
          - -c
          - |
            PEERS="etcd-0=http://etcd-0.trusted-cluster-01-etcd:2380,etcd-1=http://etcd-1.trusted-cluster-01-etcd:2380,etcd-2=http://etcd-2.trusted-cluster-01-etcd:2380"
            exec etcd --name ${HOSTNAME} \
              --listen-peer-urls http://0.0.0.0:2380 \
              --listen-client-urls http://0.0.0.0:2379 \
              --advertise-client-urls http://${HOSTNAME}.trusted-cluster-01-etcd:2379 \
              --initial-advertise-peer-urls http://${HOSTNAME}:2380 \
              --initial-cluster-token etcd-cluster-1 \
              --initial-cluster ${PEERS} \
              --initial-cluster-state new \
              --data-dir /var/run/etcd/default.etcd
              --cert-file /var/certs/etcd/trusted-cluster-01-etcd.trusted-cluster-01.svc.cluster.local.pem \
              --key-file /var/certs/etcd/trusted-cluster-01-etcd.trusted-cluster-01.svc.cluster.local-key.pem \
              --trusted-ca-file /var/certs/etcd/trusted-cluster-01-etcd.trusted-cluster-01.svc.cluster.local.ca.pem \
              --client-cert-auth  \
              --auto-compaction-retention 1 \
              --auto-compaction-mode periodic \
              --metrics extensive \
              --logger 'zap'
        ports:
        - containerPort: 2379
          name: client
        - containerPort: 2380
          name: peer
        volumeMounts:
        - name: data
          mountPath: /var/run/etcd
        - name: etcd-certs
          mountPath: /var/certs/etcd
      volumes:
        - name: etcd-certs
          configMap:
            name: etcd-certs
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
