---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  labels:
    app: teleport-db
data:
  my.cnf: |-
    [client]
    port   = 3306
    socket   = /var/run/mysqld/mysqld.sock
    default-character-set=utf8

    [mysql]
    default-character-set=utf8
    [mysqld_safe]
    pid-file = /var/run/mysqld/mysqld.pid
    socket   = /var/run/mysqld/mysqld.sock
    nice   = 0
    [mysqld]
    pid-file        = /var/run/mysqld/mysqld.pid
    socket          = /var/run/mysqld/mysqld.sock
    datadir         = /var/lib/mysql
    secure-file-priv= NULL

    require_secure_transport=ON
    ssl-ca=/var/teleport/certs/server.cas
    ssl-cert=/var/teleport/certs/server.crt
    ssl-key=/var/teleport/certs/server.key

    !includedir /etc/mysql/conf.d/
---
apiVersion: v1
kind: Service
metadata:
  name: teleport-db-mysql
  labels:
    app: teleport-db
    role: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: teleport-db
    role: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teleport-db-mysql
spec:
  selector:
    matchLabels:
      app: teleport-db
      role: mysql
  template:
    metadata:
      labels:
        app: teleport-db
        role: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0.27
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "rootpassword"
            - name: MYSQL_USER
              value: appuser
            - name: MYSQL_PASSWORD
              value: appuserpasswd
            - name: MYSQL_DATABASE
              value: teleport-db
          volumeMounts:
            - name: mysql-config
              mountPath: /etc/mysql/my.cnf
              subPath: my.cnf
            - name: data
              mountPath: /var/lib/mysql
            - name: teleport-certs
              mountPath: /var/teleport/certs
      volumes:
        - name: mysql-config
          configMap:
            name: mysql-config
        - name: teleport-certs
          configMap:
            name: teleport-mysql-certs
        - name: data
          emptyDir: {}
