apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base

resources:
- teleport-client.yaml
- etcd-certs-configmap.yaml
- etcd.yaml

patchesStrategicMerge:
- config.yaml
- deployment.yaml
