apiVersion: v1
kind: Service
metadata:
  name: teleport-metrics
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "3000"
spec:
  type: ClusterIP
  selector:
    app: teleport
  ports:
  - name: metrics
    port: 9090
    targetPort: 3000
    protocol: TCP
