apiVersion: v1
kind: ConfigMap
metadata:
  name: etcd-certs
data:
  root-cluster-etcd.root-cluster.svc.cluster.local-key.pem: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEAuX47XLxzRbRsFkLX1I0ZZIxait6Af7qnicnU3NU+kOHLDyK8
    GxrM9+LYEwSPA4HvWYHkYXt4klHkKe5KBeXwgjzNzXg8fbKpoKWcL4ZX8y8G6uVp
    5hp7WTGGI8/gxOC1tA6TAzf96O+kYovMeoElrqLvZjmJcduj236Yxt4q2gGppEW4
    SJyvnqfe4N8UKf9Cjl46/ulHwOehH0053ahDwiRJiMtc35N5Ajpx/wwlN4SnUH+B
    LNV91m3VCX6XWorD62X9SU3K+JK7rqOWa5My62gA7jqTxg1xxjs2Y8AkYCg99XJm
    wzX+TR+VQphxQlxKZLiyUyEq3CLXxKXNSsWRFQIDAQABAoIBAFHBPj64XIILbFw/
    Z8spyVhUuA9e0/n39aG4UFZosmO+8PWh1JCJtm9HDv8K0lG0ch7cLiF8/v5Wk56b
    hQqmduOgEwENjnPETBkfBQC5UIhBYOYk6RDe+SCtwDaGh8WeWNecWNVhV0rUXHqG
    rUANLeOTsro2f8qsCMNUP9fe0bo1o0uiCth9VVcairy/1HcLqgfcyXI0yZCCNh/4
    Hi+ZCBPW2MAj9E7Qd2YRn0YfjMotLWFKzKXmsaZQynYAb/xKY55oxD5jgT/lxKXJ
    sMZKkOVH23g8RbPM8f3LYQap0h4XnnSBibgDu/ekVK2t7BSC+GkffUgCL3shjW3Z
    x3VXLaECgYEA2DNAItiscyIkgv7ZIWCCSjxZRF6+J/CsZDtmS+1/Pk2+D9SqcemT
    cbgTs3MNW9VDAX/jT0He0UO4MqFqfUS5b/bzbIHT+xYAgO87oAo0k60g9gikq/+v
    7RLUtrhBiYW21YUogI+sAtN08j0N9/Xx4uzJH1Won9JUrlIHOda4ybkCgYEA26Pd
    Q097RHfDhIQVBaFdjQqNS8mnH/GXu4l9vsOq2rX79L4p76R7krRctNpw3BGh6ObP
    R8Icuc4YQseOwNuPRBVgxbJ7dHHWTJ5vCew+38Pru2f58sypNTshPPEoL7Qhuibj
    OPTkqDcmK+yWRbIh/Mu73YxBE2gGVDTzYXdpgD0CgYEAtLNhT765pCFNUw+ee38m
    ZtW55qMpXEiUTdI31g5S48gmqyScsUkAq3OnQ71N1QuSTZaObpgnm9B2DBtN3hWq
    yCInovGAM8RX92v88e6Vszho7DqdKAU1DXlHwNCQNllET4JUL9/lbRdAD5doLW+r
    FHfEQiReI/awQGLfF0CYgkECgYAn5EAonIP38ISbSd4DksZJ+pOlIy/udlOnpRYo
    kqMybAEh93PoaYhkIcwAsPf0kGNGyLz2/IN5H7x6TIJZ9sazh+p2na8cfBx+9/uU
    4sqcm5nyBLV56sAEwgOMbQRufZnulGeKjbgF8VZGfgbhC7RulJY/a9zZ6HfVzXQy
    zJxlxQKBgA+4JH+AWP7m9n/xvG8mn4QWrb6X6/tZSnI6eSDbM5Geze/AQsibWfmv
    s0sIOhcYSFrXeqBNuj4nqa3vKfA8ReTyWxUvCQMgvVRi3MBydT9ZOKFrkIcwhIvK
    /s+ODXXShtNWMpBawfwf6BEzWIu0zikmtG0ZHCXJAAm4e7hQJ49A
    -----END RSA PRIVATE KEY-----
  root-cluster-etcd.root-cluster.svc.cluster.local.ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIDWjCCAkKgAwIBAgIUVQzKJFIW8qXeb/KAXBDb8+kFaigwDQYJKoZIhvcNAQEL
    BQAwRTELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAk5ZMREwDwYDVQQHEwhOZXcgWW9y
    azEWMBQGA1UEAxMNVGVsZXBvcnQgRVRDRDAeFw0yMTExMjgxNzM2MDBaFw0yNjEx
    MjcxNzM2MDBaMEUxCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJOWTERMA8GA1UEBxMI
    TmV3IFlvcmsxFjAUBgNVBAMTDVRlbGVwb3J0IEVUQ0QwggEiMA0GCSqGSIb3DQEB
    AQUAA4IBDwAwggEKAoIBAQCsxKFV9Z6kleK2RHYByaYeuT/Swhzpj9le3zr8zIYh
    I13hQFDcYb1eszsRSnTjhwe5JOsZd38qYNozfFBDyADurc+yMnr1p/J6VJ7fHs4f
    eMERsCWHSDjbj1mRIOGkuZAYBiUozvm9p/qkdch7Qkr4Mt6bzv+/lOStFs73+Zi3
    DcKRbcqCt1pnt47+S8O16FFyK+z7DIJq8toJ9ThiZ+b9ndWl2/kmcGBe5agix8Zk
    Q1WKrD0uXSRAd9PsalNOv5L/7eRaqt1hqafz/5NYXgvXMRhYW+yu99eJUNowP+J9
    eDQE9Is1e8dixWgU5oiPKzrcEYA8EqiZ1zBRhRtZvr75AgMBAAGjQjBAMA4GA1Ud
    DwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBSmZkOsb3Xncu+r
    HZ25Ne7pmgm0kDANBgkqhkiG9w0BAQsFAAOCAQEAF2NQe3ci2ffZ5TlzVpIpz9eN
    48Yh9Dx9/Htwxx+KqQv7WIlaSu/Rq75nUAPeH6jjU2d029ewty0C4415Jsld4TdW
    HsTzpp82ULGJruvXHiWo7Zxj29+tBkYfO26t2EElQLsXUZV/N5tNlQHUclO7Hgkf
    Dgh4Cbqy9j+69eT6SqXNu7QL89MbAXAwKlPQ3Q364C9rJxsY5TT8dWokKCYVB5JJ
    niEZSwgKPLNIs6QvPu3rUDHy4RpVHlU05i498ot3bJjHIpYmqNEhCyLq+ln1TC9f
    vqJIW2as7H/Vzb/IYk0fZTMUKibYzVfFZxHC8cCucRtw6FsolcAOE4zMrKtLew==
    -----END CERTIFICATE-----
  root-cluster-etcd.root-cluster.svc.cluster.local.csr: |
    -----BEGIN CERTIFICATE REQUEST-----
    MIICzjCCAbYCAQAwOzE5MDcGA1UEAxMwcm9vdC1jbHVzdGVyLWV0Y2Qucm9vdC1j
    bHVzdGVyLnN2Yy5jbHVzdGVyLmxvY2FsMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
    MIIBCgKCAQEAuX47XLxzRbRsFkLX1I0ZZIxait6Af7qnicnU3NU+kOHLDyK8GxrM
    9+LYEwSPA4HvWYHkYXt4klHkKe5KBeXwgjzNzXg8fbKpoKWcL4ZX8y8G6uVp5hp7
    WTGGI8/gxOC1tA6TAzf96O+kYovMeoElrqLvZjmJcduj236Yxt4q2gGppEW4SJyv
    nqfe4N8UKf9Cjl46/ulHwOehH0053ahDwiRJiMtc35N5Ajpx/wwlN4SnUH+BLNV9
    1m3VCX6XWorD62X9SU3K+JK7rqOWa5My62gA7jqTxg1xxjs2Y8AkYCg99XJmwzX+
    TR+VQphxQlxKZLiyUyEq3CLXxKXNSsWRFQIDAQABoE4wTAYJKoZIhvcNAQkOMT8w
    PTA7BgNVHREENDAygjByb290LWNsdXN0ZXItZXRjZC5yb290LWNsdXN0ZXIuc3Zj
    LmNsdXN0ZXIubG9jYWwwDQYJKoZIhvcNAQELBQADggEBAAj4cZQc7waD5rh2y2cc
    vSruAGV4+seQa89O4Q/NVJ0qqkXzlojmO5GRZW40HLE0wcRMXkO96Emxy2XfFdMj
    yLE0q/fs2b3tBpQsOfuOiJ8mfNWRzJGN+H/meioZ6PreHAJ+rRwICvVI4FMj9B/n
    F0mPuAe2uvluT4exJknC3NR3+zIBxRVwhyHIwOmPO5KxorbJmaaQV/xqrm6X19gF
    P9Zr5N6yYnMs23qhG6gapv8HNZYi+JpEDyyjEtgNd/nKVbRbkQQfeKjvhFQbuolZ
    cqesIDxC9ePaWWw7YxSR6kBxfg1zks4iVDU145jziJ5mEGuT+4j6qxHK8e8+ufcX
    yVE=
    -----END CERTIFICATE REQUEST-----
  root-cluster-etcd.root-cluster.svc.cluster.local.pem: |
    -----BEGIN CERTIFICATE-----
    MIIDwjCCAqqgAwIBAgIUH7HnIJjOH5dhG17TIU1CZu9g2BcwDQYJKoZIhvcNAQEL
    BQAwRTELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAk5ZMREwDwYDVQQHEwhOZXcgWW9y
    azEWMBQGA1UEAxMNVGVsZXBvcnQgRVRDRDAeFw0yMTExMjgxNzQwMDBaFw0zMTEx
    MjYxNzQwMDBaMDsxOTA3BgNVBAMTMHJvb3QtY2x1c3Rlci1ldGNkLnJvb3QtY2x1
    c3Rlci5zdmMuY2x1c3Rlci5sb2NhbDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
    AQoCggEBALl+O1y8c0W0bBZC19SNGWSMWoregH+6p4nJ1NzVPpDhyw8ivBsazPfi
    2BMEjwOB71mB5GF7eJJR5CnuSgXl8II8zc14PH2yqaClnC+GV/MvBurlaeYae1kx
    hiPP4MTgtbQOkwM3/ejvpGKLzHqBJa6i72Y5iXHbo9t+mMbeKtoBqaRFuEicr56n
    3uDfFCn/Qo5eOv7pR8DnoR9NOd2oQ8IkSYjLXN+TeQI6cf8MJTeEp1B/gSzVfdZt
    1Ql+l1qKw+tl/UlNyviSu66jlmuTMutoAO46k8YNccY7NmPAJGAoPfVyZsM1/k0f
    lUKYcUJcSmS4slMhKtwi18SlzUrFkRUCAwEAAaOBszCBsDAOBgNVHQ8BAf8EBAMC
    BaAwEwYDVR0lBAwwCgYIKwYBBQUHAwEwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQU
    eso8vCvZQi9/C/5H9XlGu0zVnZEwHwYDVR0jBBgwFoAUpmZDrG9153Lvqx2duTXu
    6ZoJtJAwOwYDVR0RBDQwMoIwcm9vdC1jbHVzdGVyLWV0Y2Qucm9vdC1jbHVzdGVy
    LnN2Yy5jbHVzdGVyLmxvY2FsMA0GCSqGSIb3DQEBCwUAA4IBAQCYl1Eaz862QW35
    CIbzLl49DYlIgV/0aCox9dixJKWFqgMEheUUhXAWVEgIuhL/g13R2pqWCV03HTu/
    Gcn9Lgqc0ab3qpSBRku0N9m6aSTWR4GVtQJDQ6LBq5bmNzRlINXb0ixwooWx/opF
    McS9S+i9A7d7EyB6TVo4CGCp9ELiJzXUSpYKfAHpMMiAoU3lqXgXKpCPxp3x9Wcz
    DRFyvTAdFb0U7811eRTZ5kd+t76J3dpwXBjlhFHdwrDyjB3T+KSSMyEFX+3/F5H0
    qqptpXYEsFPzhFHC/mMyvEpPjFZBfXYRfcLK6qEmU18wwq2jNCBW/cF3+5+9AOOD
    57IGRmPC
    -----END CERTIFICATE-----
