# Source: teleport-cluster/templates/config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: teleport
data:
  teleport.yaml: |
    teleport:
      log:
        severity: INFO
        output: stderr
    auth_service:
      enabled: true
      cluster_name: teleport.standalone.svc.cluster.local
      authentication:
        type: local
        second_factor: off
    kubernetes_service:
      enabled: false
      listen_addr: 0.0.0.0:3027
      kube_cluster_name: teleport.standalone.svc.cluster.local
    proxy_service:
      public_addr: 'teleport.standalone.svc.cluster.local:443'
      kube_listen_addr: 0.0.0.0:3026
      mysql_listen_addr: 0.0.0.0:3036
      enabled: true
    ssh_service:
      enabled: false
