apiVersion: v1
kind: Service
metadata:
  name: teleport-management
  labels:
    app: teleport
spec:
  type: ClusterIP
  ports:
  - name: management
    port: 3025
    targetPort: 3025
    protocol: TCP
  selector:
    app: teleport
