apiVersion: v1
kind: Service
metadata:
  name: teleport-metrics
  labels:
    app: teleport
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: teleport
